-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, date_format(R.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD AS B, USED_GOODS_REPLY AS R
WHERE B.BOARD_ID = R.BOARD_ID and YEAR(B.CREATED_DATE) = 2022 and MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE, TITLE